# Sensors/Model covariances
localization/dvl_covariance: [0.002, 0.002, 0.002] # computed wrt bottom
localization/gps_covariance: [0.5, 0.5]
localization/model_covariance: [0.02, 0.02, 0.02]

#If DVL velocity is bigger than "localization/dvl_max_v" in m/s it puts it to 0.0
localization/dvl_max_v: 1.0
localization/gps_update: False
