# safety_g500/mission_time_out: 30 --> Defined in mission.yaml file
safety_g500/heart_beat_period: 10.0
safety_g500/periodic_check: 2.0
safety_g500/max_battery_level_period: 10
safety_g500/max_internal_sensors_period: 10
safety_g500/max_nav_sensors_period: 5
safety_g500/max_humidity: 90.0
safety_g500/max_pressure: 1200.0
safety_g500/max_temperature: 60.0
safety_g500/min_battery_level: 15.0
safety_g500/max_init_time: 30.0


